spring: 
  profiles: 
    active: 
    - dev

---
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-sirius-dev

---
spring: 
  profiles: test
  applicaiton: 
    name: microservicecloud-config-sirius-test
  